### ISSUE TITLE
Offline Sync for android sdk is not working

### ISSUE THREAD

**Issue by Navpreet2289** [Azure/azure-mobile-apps-android-client#103]
Offline Sync for android sdk is not working at all

for server version "azure-mobile-apps": "^2.0.0",
android SDK version com.microsoft.azure:azure-mobile-android:3.3.0@aar

**Comment by Navpreet2289** [comment]
if i run the sync function in main thread it works fine ... but if i run the sync function in background as mentioned in todo sample app, it does not work at all. As threads stuck in waiting. I tried todo sample app.. it does not work even.. if sync is made to run in background

**Comment by MatkovIvan** [comment]
Hi @Navpreet2289 
Sorry for the long delay.

I've tested this functionality and found no problem with it.
Please double check that you complete all the setup steps.

Setup tutorials:
- [Enable offline sync for your Android mobile app](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-android-get-started-offline-data)
- [Create an Android app](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-android-get-started)

Feel free to ask additional questions.

**Comment by elamalani** [comment]
@Navpreet2289 We haven't heard back from you. I'm closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!
