### ISSUE TITLE
SDK Dont work with Java 1.8 and Guava 22, Android Studio 3.0.0 Canary 6

### ISSUE THREAD

**Issue by omar25vx** [Azure/azure-mobile-apps-android-client#105]
SDK Dont work with Java 1.8 and Guava 22, Android Studio 3.0.0 Canary 6

Failed resolution of: Lcom/google/common/util/concurrent/SettableFuture

I need down project to Java 1.7, Guava 20

**Comment by MatkovIvan** [comment]
Hi @omar25vx 

I've checked quickstart app with SDK `3.3.0`,  `Java 1.8` and `Guava 22` on last `Android Studio 3.0 beta 7`. It works well for me. I guess this can happen because you tried it with the unstable version of Android Studio. Let me know if you still have this problem.
