### ISSUE TITLE
.invokeApi("abc?def=" + ....) fails

### ISSUE THREAD

**Issue by nor0x** [Azure/azure-mobile-apps-android-client#107]
I'm using the SDK to connect to a .NET backend hosted on Azure. The invokation of the following REST endpoint fails.

`.invokeApi("abc?def=" + someString`

The server responds with the following message:
`System.Web.HttpException: A potentially dangerous Request.Path value was detected from the client (?).`

This error has something to do with the Azure Mobile Android SDK because calling the endpoint on iOS and Postman works just fine. Anybody has an idea on how to fix this?

**Comment by MatkovIvan** [comment]
Hi @nor0x,

Thanks for getting in touch and sorry for late response.
You are trying to pass the query parameters into api name argument. SDK has `invokeApi` overload with `List<Pair<String, String>> parameters` argument for passing query parameters. Please use this overload instead.

Let me know if you have any questions.

Best,
Ivan

**Comment by elamalani** [comment]
@nor0x We haven't heard back from you. I'm closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!
