### ISSUE TITLE
MobileServiceJsonSyncTable does not sometimes update a row

### ISSUE THREAD

**Issue by omar25vx** [Azure/azure-mobile-apps-android-client#120]
In ocations I try to update a perfectly mapped and instantiated object, when with its repectivo ID, but does not update on the server, in the local database if it is updated, but not on the server, a push and pull event is performed but not it works.

It should be clarified that it does not always happen, but when I pass I have to delete the device cache, re-enter, make the modifications and it works.

It does not show error of any type, it only updates local but not in server.

compile 'com.microsoft.azure:azure-mobile-android:3.3.0@aar'
compile 'com.google.guava: guava: 23.2-android'
compile 'com.squareup.okhttp: okhttp: 2.7.5'
compile 'com.google.code.gson: gson: 2.8.1'

**Comment by MatkovIvan** [comment]
Hi @omar25vx,

Thanks for getting in touch.
To identify a problem could you please answer additional questions?
1. Is this happen only on your main application or you can able to reproduce it on a sample project?
2. Do you see any errors from the server side in your application logs in the Azure Portal?

Best,
Ivan

**Comment by elamalani** [comment]
@omar25vx Were you able to fix this issue? If not, can you share more information to help us investigate it?
 Thanks!

**Comment by elamalani** [comment]
@omar25vx We haven't heard back from you. I'm closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!
