### ISSUE TITLE
Add OkHttp 3 support

### ISSUE THREAD

**Issue by GeorgePetri** [Azure/azure-mobile-apps-android-client#121]
OkHttp 3 has been out for some time, having support for It would be beneficial since OkHttp 2 doesn't appear to be maintained anymore.

**Comment by GeorgePetri** [comment]
I see the issue has been resolved. When is the next release that includes the pull request?

**Comment by NeuronKarrde** [comment]
Still no any news about next release? now azure mobile apps client is not working with the latest ok http3 lib

**Comment by GeorgePetri** [comment]
https://github.com/GeorgePetri/azure-mobile-apps-android-client/releases
