### ISSUE TITLE
not possible to insert null values

### ISSUE THREAD

**Issue by erikmompean** [Azure/azure-mobile-apps-android-client#128]
I have a c# backend with nullable type and with swift I am able to insert null values but with Android is not possible. I have also tried to pull data using postman and it works perfect but when I use the insert method of MobileServiceSyncTable and MobileServiceJsonSyncTable is not possible. I have tried to add values manually into the json object with value JSONObject.NULL but is also not possible.

**Comment by bmourat** [comment]
Hi @erikmompean
 
Could you provide more details (code snippet, model structure) on how are you trying to insert an item into the table? I tried inserting records with null values and it worked as expected.

**Comment by elamalani** [comment]
@erikmompean We haven't heard back from you. I am closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!
