### ISSUE TITLE
Not able create the folder having two level depth.

### ISSUE THREAD

**Issue by sudarshanthite** [Azure/azure-mobile-apps-android-client#136]
HI, 

By using this android sdk we are not able to create the folder with two level folder depth.
example : suppose my azure base url is http://abc.com 
then i am able to create the folder like http://abc.com/folderlevelone but not able to create folder like 
http://abc.com/folderlevelone/folderleveltwo the sdk gives me the exception that.

The requested URI does not represent any resource on the server.

Can you pls check.

Thanks.

**Comment by sudarshanthite** [comment]
Hello @achocron , can you pls check.

**Comment by MatkovIvan** [comment]
Hi @sudarshanthite

Thank you for getting in touch and sorry for late response.
Could you please share the whole information about this exception (type, stacktrace)?
Also, please [enable logging for outgoing requests in your mobile client](https://github.com/Azure/azure-mobile-apps/wiki/Help,-my-app-isn't-working!#log-outgoing-requests-in-your-mobile-client) and share the logs.

> The requested URI does not represent any resource on the server.

It looks like the HTTP error, so the logs will be very helpful

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Feel free to reopen/comment if you have more questions or have more information about the issue.
