### ISSUE TITLE
No static method addCallback

### ISSUE THREAD

**Issue by MichelleMcCabe** [Azure/azure-mobile-apps-android-client#138]
Get the following error when calling invokeApi: 

java.lang.NoSuchMethodError: No static method addCallback(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/util/concurrent/FutureCallback;)V in class Lcom/google/common/util/concurrent/Futures; or its super classes (declaration of 'com.google.common.util.concurrent.Futures' appears in /data/app/za.co.findmyfamily.findmyfamily-1/split_lib_dependencies_apk.apk)
        at com.microsoft.windowsazure.mobileservices.MobileServiceClient.invokeApiInternal(MobileServiceClient.java:1397)
        at com.microsoft.windowsazure.mobileservices.MobileServiceClient.invokeApi(MobileServiceClient.java:1362)

It is related to Futures.addCallback being deprecated [see here](https://google.github.io/guava/releases/22.0/api/docs/com/google/common/util/concurrent/Futures.html#addCallback-com.google.common.util.concurrent.ListenableFuture-com.google.common.util.concurrent.FutureCallback-)

Documentation states: 

> Deprecated. Use the overload that requires an executor. For identical behavior, pass MoreExecutors.directExecutor(), but consider whether another executor would be safer, as discussed in the ListenableFuture.addListener documentation. This method is scheduled to be removed in April 2018.

Gradle:
implementation 'com.microsoft.azure:azure-mobile-android:3.4.0@aar'
implementation 'com.google.guava:guava:27.0.1-android'

Please upgrade invokeApiInternal so we can use it with newer method calls.

**Comment by MichelleMcCabe** [comment]
Hi Ian

Thanks for sorting this out for me.  Apologies for only thanking you almost A MONTH after the fact.  Very rude!  :-)

Have an awesome day!
Michelle

**Comment by jonasrotilli** [comment]
I'm having the same problem, I did not understand how "I update calls from # 139".
What does that mean in practice?
