### ISSUE TITLE
Log in with Client-flow Authentication and MSAL

### ISSUE THREAD

**Issue by sgallego** [Azure/azure-mobile-apps-android-client#148]
Hi all,
I'm trying to log in as describe in:
https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-android-how-to-use-client-library#log-in-with-client-flow-authentication
I'm using 'aad' as provider and **MSAL** authentication result as token:

`val payload = JSONObject()
payload.put("access_token", authenticationResult.accessToken)
val mLogin = azureclient.login(MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory, payload.toString())
        Futures.addCallback(mLogin, object : FutureCallback<MobileServiceUser> {
            override fun onFailure(exc: Throwable) {
               ...
            }
            override fun onSuccess(result: MobileServiceUser?) {
                ...
            }
        })
`

but onFailure is always called:

`com.microsoft.windowsazure.mobileservices.MobileServiceException: {"code":401,"message":"IDX10501: Signature validation failed. Key tried: 'System.IdentityModel.Tokens.X509AsymmetricSecurityKey'.\u000atoken: '{\"typ\":\"JWT\",\"nonce\":\"...`

My questions are:

- Is there any special scope I should add to MSAL authentication?
- Is there any special configuration I should do in Azure App?

Best regards.

**Comment by dtrabo** [comment]
Hello @sgallego! Sorry, but the client authentication flow only supports MSA using Live SDK and we don't have plans to support MSA through the MSAL SDK. Please look at this https://github.com/Azure/azure-mobile-apps-net-client/issues/455

**Comment by sgallego** [comment]
@dtrabo has written me, but comment was not added here. I don't know why:

> Hello @sgallego! Sorry, but the client authentication flow only supports MSA using Live SDK and we don't have plans to support MSA through the MSAL SDK. Please look at this Azure/azure-mobile-apps-net-client#455

**Comment by sgallego** [comment]
This is my situation:
- I'm using MSAL to login users. 
- I use MSAL token to get user profile and groups from Microsoft Graph:
`SCOPES = arrayOf("https://graph.microsoft.com/User.Read",
                 "https://graph.microsoft.com/Directory.Read.All")`
- I want to log in with MobileServiceClient to set 'Authenticated access only' to my Easy tables.

What alternatives do I have?
- Can I use ADAL instead of MSAL?
- Can I move to Live SDK to login users and use this token to call to Microsoft Graph?
- Can I use authentication server flow from MobileServiceClient and use this token to call to Microsoft Graph?

@dtrabo can you help me?
Best regards.

**Comment by jwallra** [comment]
Hi @sgallego

1) We recommend using ADAL, we unfortunately don't test for MSAL.
2) Don't use the Live SDK.
3) You should be able to use either server flow or client flow, depending on your use case.  Since you've already gotten started with client flow, that's a fine pattern to follow.  The authentication token works with the App Service backend for either flow, so it won't work with the Microsoft Graph API.

There is additional documentation [here](https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/backend/) that is for .NET, but it may give you some insights as to how to implement your auth flow.

**Comment by sgallego** [comment]
Finally I moved to ADAL and all is working fine.
Thanks for your help!
Best regards.
