### ISSUE TITLE
Cannot sync when using offline mode

### ISSUE THREAD

**Issue by kaymyst** [Azure/azure-mobile-apps-android-client#25]
Hi, I followed https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-android-get-started-offline-data/ with version 3.0.0 of the sdk  and a vanilla todo app from the new portal and I cannot get the sync to work at all.
any idea why?
There is no log or exception being raised.

**Comment by mamaso** [comment]
Hi @kaymyst,

I tested the offline sample and it works as expected.  Are you able to get the basic todo sample (with no offline sync) to function?

**Comment by kaymyst** [comment]
Hi @mamaso,
yes the basic example works fine online, i then comment out and enable the offline mode as per the article and then no data is coming through at all

**Comment by mamaso** [comment]
A bit more information might help

When the phone is in airplane mode, are items being saved to the local store?  
Can you not refresh with changes from the remote table?
Have you tried debugging the solution?
Have you looked at the android monitor logs?
