### ISSUE TITLE
Missing documentation SDK 3.0

### ISSUE THREAD

**Issue by Guimareshh** [Azure/azure-mobile-apps-android-client#26]
Hi there !

I'm unable to find the documentation for the SDK 3.0 of Azure Mobile. This one: https://bintray.com/microsoftazuremobile/SDK/Mobile-Apps-Android/view

We are using Mobile App, instead of Mobile Services after a migration, we have to use the SDK 3.0 of Android. I know most of the code is the same between this new version and the previous one, but some methods (the connection to the database for example) are different. I have had an information from a ticket posted on Azure postal explaining that you were working on a documentation, this information is dated from December but I don't have any news since. 

Can you help me or inform me about the documentation ?

Thanks,
Lucien Guimaraes

**Comment by RickSaling** [comment]
We are coming up with a smoother system, but for now, the JavaDocs are here
https://github.com/Azure/azure-mobile-apps-android-client/tree/master/sdk/src/sdk/doc
you can pull the repo down to your machine and then view them (index.html) in a browser

**Comment by phvannor** [comment]
Why didn't we put the doc folder on the gh-pages branch?  For iOS, we have the README as the base page, and that links into the v3 details, and can be exanded/etc when we hit v4/etc.  

See: https://github.com/Azure/azure-mobile-apps-ios-client, https://github.com/Azure/azure-mobile-apps-ios-client/tree/gh-pages

**Comment by ysxu** [comment]
This is on my list. Android should have a similar gh page as ios.

**Comment by Guimareshh** [comment]
Thanks everyone for these replies ! 

Are you going to publish something like the Azure Mobile Services documentation ? This one: https://azure.microsoft.com/en-us/documentation/articles/mobile-services-android-how-to-use-client-library/

**Comment by Guimareshh** [comment]
I had a reply on Twitter from Azure Mobile Apps, the documentation has been released: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-android-how-to-use-client-library/

Thanks everyone !
