### ISSUE TITLE
Unable to use local auth stubs

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-mobile-apps-android-client#29]
There is an issue with how the login window constructs it’s URLs – it ignores ports in URLs. This is not going to be an issue when it’s hosted, I don’t think Antares will ever run on anything but standard ports, but for my local auth stub, it only works when running on port 80. The issue lies here.

**Comment by phvannor** [comment]
why are you hitting a local stub?  I thought all auth is supposed to go to the cloud for local debugging via the loginHost on client?

**Comment by soninaren** [comment]
#42
