### ISSUE TITLE
I never get from server field __createdAt

### ISSUE THREAD

**Issue by icsd** [Azure/azure-mobile-apps-android-client#32]
The field __createdAt is not contained in the responses I get from the server while synchronizing a table. Does this happen on purpose?

**Comment by mamaso** [comment]
For mobile apps __createdAt has been renamed to simply createdAt.  It's possible that there is stripping behavior going on, is this at the sdk level or in the http responses?  What backend are you using, node or .net?

**Comment by icsd** [comment]
It is in the http responses. I am using .net backend.

**Comment by mamaso** [comment]
Hi @icsd, I took a look & this is the consistent behavior across platforms.  If you would like to access createdAt/updatedAt/deleted columns on the client you can add those to the table definition and they should be populated.
