### ISSUE TITLE
com.microsoft.windowsazure.mobileservices.MobileServiceException: {"code":401,"error":"Error: Unauthorized"}

### ISSUE THREAD

**Issue by Guimareshh** [Azure/azure-mobile-apps-android-client#35]
Hi there,

I have an issue when I try to retrieve all datas from a specific table. I'm using the version 3.0 of the SDK. I had the same issue after migrated iOS SDK of Azure to 3.0. It was an issue about the "ApplicationKey" who is now read-only and not set in the constructor of MobileServiesClient. We had to create a custom class to fix it, but on Android there is no ApplicationKey value on MobileServiesClient unlike iOS SDK (https://github.com/Azure/azure-mobile-apps-ios-client/blob/master/sdk/src/MSClient.h#L53). 

Also there is no reference of this attribute on the new doc for Mobile Apps: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-android-how-to-use-client-library

And my permissions on all tables is set to "Anybody with the Application Key".

**Comment by mamaso** [comment]
In mobile apps we have removed the concept of "application key".  It sounds like you are using a mobile service backend with the 3.0 SDKs, which are intended for mobile apps.  You should not use the 3.0 SDKs unless if you are migrating the backends to mobile apps from mobile services as well.

Here is the documentation for Mobile Apps, if that helps clarify - https://azure.microsoft.com/en-us/documentation/services/app-service/mobile/

**Comment by Guimareshh** [comment]
Indeed, we were using Mobile services. But we are using the 3.0 SDK because we have migrated our service backend to Mobile App (during November). As you can see on the following screenshot of the Azure Portal, we are using Mobile Apps :

![mobile_apps](https://cloud.githubusercontent.com/assets/9654353/12744385/44e6eb6c-c994-11e5-8a65-88d477f94e15.png)

As we used the automatic migration on Azure Portal, is it possible an issue occurred during this migration ?

**Comment by mamaso** [comment]
Ok, I see the confusion, let me try to clarify.

Clicking the 'migrate to app service' button in the portal does not change a mobile service to a mobile app.  It moves the mobile service from mobile services hosting to azure websites hosting, which provides a bunch of benefits like staging slots, etc.

For a migrated mobile service the latest sdk is 2.0.3, this is the sdk that you should be using.  Writing a shim around the new 3.0 sdk is definitely not sustainable.

Hopefully that clears things up.

**Comment by Guimareshh** [comment]
Ok I understand now why I have this issue. But to be honest, it was not clear at all on Azure Portal. Why our mobile service has been moved to mobile app in the dashboard, if technically it's not like that ?  

As you can see on my screenshot it's written "Mobile App" not "Mobile services". It should be on "Mobile Services (classic)" instead of "Mobile Apps":

![screen shot 2016-02-03 at 09 58 00](https://cloud.githubusercontent.com/assets/9654353/12777327/8057e3c2-ca5c-11e5-92c2-e03a54703f8b.png)
![screen shot 2016-02-03 at 09 58 11](https://cloud.githubusercontent.com/assets/9654353/12777333/84d676e8-ca5c-11e5-8341-8dd212a58d88.png)

I close the issue, I hope the Azure portal will be improved to avoid this huge confusion.

**Comment by paulbatum** [comment]
> Clicking the 'migrate to app service' button in the portal does not change a mobile service to a mobile app.

I don't quite agree with this statement from @mamaso, I think it adds to the confusion. The reality is that there is virtually no difference between a web app and a mobile app - there is an icon and a few other small UI tweaks, but that is about it.

A user can be in one of the following states:
- They have a Mobile Service (and they manage it from the older Azure portal)
- They have a web/mobile app that is the result of executing an App Service Migration for a Mobile Service. An app in this state still uses the older version of the server and client SDKs (e.g. Android client SDK 2.0.3).
- They have a brand new web/mobile app. The app should be using the newest version of the server and client SDKs (e.g. Android client SDK 3.0).

@Guimareshh hopefully that makes sense. If you have any specific suggestions about modifications we could make to the Azure portal to make this less confusing, I'd love to hear them.
