### ISSUE TITLE
[Push]Convert JObject to string for andriod template parameter's body

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-mobile-apps-android-client#41]
Sample template in an installation:
templates: {
        "templateName1" : {
            body: "<This can be a string or JSON>"
        }
    }

See following issue for more details:
https://github.com/Azure/azure-mobile-apps-net-client/issues/25

**Comment by mamaso** [comment]
@ysxu What is the push registration api supposed to look like?  Currently android has register(pnsHandle) and registerTemplate(pnsHandle, templateName, templateBody) which doesn't seem to match other platforms...
