### ISSUE TITLE
Post the JavaDocs for the Android Client in github pages

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-android-client#45]
For reference on github pages: https://pages.github.com/

Please generate the javadocs and check them in so that they appear in github pages.
Add a link in the README.md to point to the JavaDocs

Update the build process so that the github pages are generated on release.

**Comment by soninaren** [comment]
Java docs is up and live at http://azure.github.io/azure-mobile-apps-android-client/

Code for javadocs present here.
https://github.com/Azure/azure-mobile-apps-android-client/tree/gh-pages

**Comment by soninaren** [comment]
Links updated in readme.md page
