### ISSUE TITLE
Support Auth token refresh logic

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-android-client#55]
Per http://cgillum.tech/2016/03/07/app-service-token-store/

We need to support client.refresh() that will refresh the auth tokens. A basic implementation that calls the refresh with X-ZUMO-AUTH and sets the mobile service auth token before resolving/rejecting the token would be enough to start.

**Comment by icsd** [comment]
The implementation of RefreshTokenCacheFilter does not work after moving to App Service, because `getStatusCode` is not used.
Does this issue refer to what I wrote above, or should I open a new issue?

**Comment by adrianhall** [comment]
I'm pretty sure it isn't the same.  You should open a new issue.  Provide as much information as you can.

**Comment by icsd** [comment]
Ok, I opened it [here](https://github.com/Azure/azure-mobile-apps-android-client/issues/75).
