### ISSUE TITLE
Azure Mobile should accept the new Google issuer in the tokens

### ISSUE THREAD

**Issue by MagnusJohansson** [Azure/azure-mobile-apps-android-client#56]
I'm using client side login, thus passing the token to the login method:

```
JsonObject loginBody = new JsonObject();
loginBody.addProperty("id_token", idToken);
ListenableFuture<MobileServiceUser> mLogin = mActivity.getmClient().login(MobileServiceAuthenticationProvider.Google, loginBody);
```

This works fine for idTokens issued by the , now deprecating, Google+ APIs on Android.
The JWT token issuer is accounts.google.com

```
{
  "iss": "accounts.google.com",
...

```

But when using the new and by Google recommended way to do application sign-in on Android apps, the idToken now (Since Google Play Service v8.3 or newer) the issuer field is https://accounts.google.com

> // If you retrieved the token on Android using the Play Services 8.3 API or newer, set
>     // the issuer to "https://accounts.google.com". Otherwise, set the issuer to 
>     // "accounts.google.com". If you need to verify tokens from multiple sources, build
>     // a GoogleIdTokenVerifier for each issuer and try them both.

Ref: https://developers.google.com/identity/sign-in/android/backend-auth#calling-the-tokeninfo-endpoint

```
{
  "iss": "https://accounts.google.com",
...

```

And sure enough,  now the Azure Mobile Service servers barfs this exception at me:
Error while authenticating user. {"code":401,"error":"Error: The id_token issuer is invalid."}

Please change the token validator on the Azure Mobile backend to accept these new tokens.

**Comment by ndoctor13** [comment]
Has there been any updates on this? I keep getting token issuer is invalid. How can I solve this problem with the Google Services v9.0 and newer?

**Comment by cgillum** [comment]
Are you using the more recent Azure Mobile Apps (part of Azure App Service) or the older Azure Mobile Services?  This error message is not familiar to me, so I'm guessing it comes from the older Azure Mobile Service. The more recent Azure Mobile Apps backend should be using the correct issue for Google logins.

Adding @adrianhall to comment on whether we are still making updates to Mobile Services.

**Comment by ndoctor13** [comment]
Thank you for responding. I am using mobile services android sdk 2.0.3. I want to migrate to Azure App services but it will take some effort for me to change my client side code so trying to put that extra effort on the side right now. If you are still updates Mobile Services then that would be perfect.

**Comment by adrianhall** [comment]
We are not updating Mobile Services any more. Ref: https://github.com/azure/azure-mobile-services 

The recommendation is to transition your app to App Service Mobile Apps, using the latest capabilities.  I'm going to close this as a result.  See https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-node-backend-upgrading-from-mobile-services
