### ISSUE TITLE
IS NULL / IS NOT NULL

### ISSUE THREAD

**Issue by vernazza** [Azure/azure-mobile-apps-android-client#58]
I've some date field that can be null, but it seems that there's no way to add in the query something like "IS NULL" or "IS NOT NULL".

Currently it seems that the only way to resolve this requirement is to query every row and then filtering by code...

**Comment by bmourat** [comment]
Hi @vernazza 

You can use something like this for IS NULL:
```
myTable.where().field("MyName").eq((String)null)
```

and for IS NOT NULL
```
myTable.where().field("MyName").ne((String)null)
```

**Comment by elamalani** [comment]
@vernazza Please change your query to use guidelines above. I am closing this issue for now but feel free to contact us if you have questions. Thanks!
