### ISSUE TITLE
'authorization_code' field is required

### ISSUE THREAD

**Issue by lrz-hal** [Azure/azure-mobile-apps-android-client#6]
I try to login into mobile app on android.

Here is my code
```java
 JsonObject loginBody = new JsonObject();
                        loginBody.addProperty("access_token", idToken);
                        ListenableFuture<MobileServiceUser> mLogin = mClient.login("google", loginBody);
```

Login throws an error `authorization_code field is required`.

`mClient.login("google")` works, but it returns a short_life token.

 I use `azure-mobile-android:3.0` sdk. 

Thanks,

Martin

**Comment by phvannor** [comment]
@mattchenderson can you link to the guide on google client flows that covers how to get the authorization_code field now.

**Comment by phvannor** [comment]
Response at https://github.com/Azure/azure-mobile-apps-net-server/issues/63
