### ISSUE TITLE
MobileServiceSyncContext push() over writing URL Path

### ISSUE THREAD

**Issue by JamesWhitfield** [Azure/azure-mobile-apps-android-client#65]
If you host your app services any lower then the domain root, the additional path data of the URL is lost. 

Example

`new MobileServiceClient(
                    http://mywebsite.com/myservices/,
                    context)`

any call that is performed by the syncContext push will have '/myservices/' removed.

`MobileServiceSyncContext syncContext = mClient.getSyncContext();
                    syncContext.push().get();`

The call sent out by the frame work will be as followed.

`http://mywebsite.com/tables/workorder`

where as what we would expect to see is

`http://mywebsite.com/myservices/tables/workorder`

This does not happen on a pull. Upon a pull request the path is left on. 

The over write happens on line 139 of MobileServiceHttpClient.java in 3.1.0

`Uri.Builder uriBuilder = Uri.parse(mClient.getAppUrl().toString()).buildUpon();
        uriBuilder.path(path);`

I believe this scenario could be solved by using `uriBuilder.appendPath(path)`

**Comment by adrianhall** [comment]
The Android Client is designed to operate against an Azure Mobile Apps backend running within Azure.  The behavior you are observing is by design.
