### ISSUE TITLE
null content is passed on the delete method

### ISSUE THREAD

**Issue by edwinlxl** [Azure/azure-mobile-apps-android-client#66]
at line 728 of the MobileServiceJsonTable.java, a null content is passed to the Http request, so we can't get the item data with req.body in the Node.js backend.

`ListenableFuture<Pair<JsonObject, ServiceFilterResponse>> internalFuture = this.executeTableOperation(TABLES_URL + mTableName + "/" + id.toString(), null, HttpConstants.DeleteMethod, requestHeaders, parameters, features);`

However, at Line 160 of the MobileServiceHttpClient.java file, a content parameter is passed. 
Can we change the delete method so that we can pass the item data through HTTP Request.

```
} else if (httpMethod.equalsIgnoreCase(HttpConstants.DeleteMethod)) {
            request = ServiceFilterRequestImpl.delete(mClient.getOkHttpClientFactory(), url, content);
```

**Comment by adrianhall** [comment]
The DELETE method only requires the ID - if you need the content within the backend, you will need to read the current value from your SQL database.
