### ISSUE TITLE
Patch method result is case sensitive and uppercase letters are not handled correctly

### ISSUE THREAD

**Issue by MonRoyals** [Azure/azure-mobile-apps-android-client#67]
Hi,
I have the following configuration. All my fields in the DTO (client and server) and the table definition of the local store start with an uppercase letter. The response from the server after an update/patch operation contains all fields starting with a lowercase letter.
The issue is in the MobileServiceTable::patchOriginalEntityWithResponseEntity() method, because it's case sensitive. After patching the Json object all fields are there twice. One starting with an upper case letter (the original value) and one starting with the lower case letter (the result from the server). The resulting sql statement is wrong (twice as many fields as the entity has) and the fields, which were changed on the server (UpdatedAt, Version) are not updated correctly.

I try to illustrate it with one field:
1. Sending "UpdatedAt" to the server
2. Receiving "updatedAt" from the server
3. Patching the JsonObject leads to an object with the fields ["UpdatedAt", "updatedAt"]
4. The following Sql statement is generated: 
    Update table ("UpdatedAt", "updatedAt") set (originalValue, serverValue);
5. The result is that the UpdatedAt field is not updated. Remember: All fields (DTOs and table definitions) are defined with a uppercase letter.

Thanks

**Comment by adrianhall** [comment]
You need to rename the fields on the wire.  There is generally a method in the JSON library for doing this during JSON export.  The system fields are createdAt, updatedAt, id, version and deleted - lower case.
