### ISSUE TITLE
com.microsoft.windowsazure.mobileservices.table.MobileServiceConflictException

### ISSUE THREAD

**Issue by Guimareshh** [Azure/azure-mobile-apps-android-client#69]
Hi everyone,

Since few days I'm facing an issue with Azure Mobile Apps SDK (Android: 2.0.3 because of  Azure Mobile Services) I can't resolved. Here is the issue : 

`com.microsoft.windowsazure.mobileservices.table.MobileServiceConflictException: {"code":409,"error":"Error: Could not insert the item because an item with that id already exists."}`

The user (from China) tried to create an account (his ID is not set in the code). Here is the how the user looks like before the insert request :
`id: 0
firstName: r
lastName: b
country: CN
language: zh
email: someUserMail@gmail.com
lastConnection: 2016-07-29T00:57:50.000Z
`

As you can see the id is 0 (because it's an int by default, so if not set the value = 0). My app is running since December and it's the first time I have this issue with some users. I have tried my self (from France) and I don't have an exception with this user information :

`id: 0
firstName: Lucien
lastName: Appsolute
country: ZZ
language: fr
email: someOtherMail@gmail.com
lastConnection: 2016-07-29T09:31:12.000Z
`

Do you have any idea why this exception is happening ?

**Comment by adrianhall** [comment]
Without looking at the code, no.  You need to refer to your database and see if there is stray data.
