### ISSUE TITLE
Android Quickstart Exception on Startup

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-android-client#71]
@shrooty1102 raised the following issue in the Node.js gitter channel:

Hi folks Let me know if this is the right place for this question - I have a Android Client app for the Sample Azure Mobile App (todoApp)
But its failing with the below error - Error:(95, 23) error: no suitable constructor found for MobileServiceClient(String,ToDoActivity)
constructor MobileServiceClient.MobileServiceClient(String,String,Context) is not applicable
(actual and formal argument lists differ in length)
constructor MobileServiceClient.MobileServiceClient(MobileServiceClient) is not applicable
(actual and formal argument lists differ in length)
constructor MobileServiceClient.MobileServiceClient(URL,String,Context) is not applicable
(actual and formal argument lists differ in length)
Why is a sample downloaded directly from Quickstart failing? how do i resolve it?

**Comment by soninaren** [comment]
@dhei do you want to take a look at this?
Would be a good place to start.

**Comment by dhei** [comment]
@shrooty1102: Do you see this error on a newly downloaded quickstart project? 

Do you see this error coming from this line?
```java
mClient = new MobileServiceClient(
                    "<your-app-url>",
                    this).withFilter(new ProgressFilter());
```

**Comment by dhei** [comment]
Close it for non-repro. Feel free to reactivate if it repro.
