### ISSUE TITLE
Refresh Token - App Service

### ISSUE THREAD

**Issue by icsd** [Azure/azure-mobile-apps-android-client#75]
The implementation of `RefreshTokenCacheFilter` does not work after moving to App Service, because `getStatusCode()` is not used anymore.
The code for the implementation can be found [here](https://github.com/Azure/azure-content/blob/master/includes/mobile-android-authenticate-app-refresh-token.md)

Among others this problem was discussed extensively [here](https://github.com/Azure/azure-mobile-services/issues/776), but now the page throws a 404 error.

**Comment by icsd** [comment]
If you replace `getStatusCode()` with `code` seems to play correctly.

**Comment by adrianhall** [comment]
Hi @icsd - you have referenced an AAD + Mobile Services topic.  This is not an App Service topic.  Please ensure you are following the right instructions.  I don't see an issue right now due to this.

Thanks,

**Comment by adrianhall** [comment]
Closing for lack of response.
