### ISSUE TITLE
Should I define System Properties for each table of the client DB?

### ISSUE THREAD

**Issue by icsd** [Azure/azure-mobile-apps-android-client#77]
Should I also define System Properties (`updatedAt`,  `createdAt`, `version`, `deleted`) when I define a table in my SQLite DB?
If I don't define them, I will not see them in my database's table, as columns. Should they be auto created from the Android Azure SDK?
If I define them, I will see them in my database's table,  as columns, and they will also have values after the synchronization.
What's the correct practice?

I am using 3.1.0 version of the android azure sdk.

**Comment by adrianhall** [comment]
Define the columns in your models on the client side.
