### ISSUE TITLE
Push failure in case of updating from Mobile Service to App Service

### ISSUE THREAD

**Issue by icsd** [Azure/azure-mobile-apps-android-client#78]
Assume the following senario:
1) A user has an app with mobile service sdk
2) There is a pending operation in the `operations` table
3) The user updates his app to a version with app service sdk
4) The push process will fail

That happens when the sdk tries to parse as String the field `createdAt` of the table operation json, which is `null`. (Because it was created by the sdk after the update of the app).
This happens in class `OperationQueue` line 188

Moreover after the migration from Mobile Service to App Service, the table `Operations` contains `__createdAt` and `createdAt` columns.

**Comment by icsd** [comment]
To avoid this bug is it safe to assign `createdAt = new Date()` ?
Does the value of `createdAt` affect the push logic?

**Comment by adrianhall** [comment]
We don't use createdAt in the sync logic, so you should be safe.

**Comment by elamalani** [comment]
@icsd This looks like an old issue opened more than a year back. Did you make changes to your app to avoid this bug? I will close it for now but feel free to reach out in case you have any questions. 

Thanks!
