### ISSUE TITLE
Database Schema Migration

### ISSUE THREAD

**Issue by icsd** [Azure/azure-mobile-apps-android-client#79]
The Android Azure SDK does not seem to handle a DB scema migration, except the senario that you add new Columns in a Table or add a new Table.

If you rename a column or if you delete a column or table, does not seem to be supported.

I had posted the same issue before some months [here](https://github.com/Azure/azure-mobile-services/issues/839) but I did not take any answer and now the link to the question does not exist.

**Comment by adrianhall** [comment]
Your best idea here is to destroy the underlying SQLite database, recreate it and resync.  It's common to store a "database version" that is incremented in code when the database schema requires such a drastic move.  The code compares the required database version to the stored database schema version and does "the right thing" on startup.
