### ISSUE TITLE
Add AlternatePushUrl setting for local development

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-android-client#81]
Handle the case when development of the server is happening locally, but App Service Push is being used.

Set client.AlternatePushUrl
If not set, use client.AlternateLoginUrl (if set)
If still not set, don't worry about it

If set to the URL of the remote backend, send the push requests there instead of localhost.

**Comment by elamalani** [comment]
Closing this issue as it's over a year old and we are not adding new features in Azure Mobile Apps.
