### ISSUE TITLE
Could not find com.android.support:customtabs:23.0.1

### ISSUE THREAD

**Issue by michael-snapptec** [Azure/azure-mobile-apps-android-client#89]
I'm trying to implement messaging from an Azure Mobile App to my Android app through FCM. I'm following the tutorial.

First error was that it could not resolve `com.microsoft.windowsazure.notifications`. I saw that the client SDK was up from 3.1.0 to 3.2.0, so I attempted to upgrade my app.

This line compiles fine in my gradle:

    compile 'com.microsoft.azure:azure-mobile-android:3.1.0'

This line breaks:

    compile 'com.microsoft.azure:azure-mobile-android:3.2.0'

The error I'm getting is:

> Error:Could not find com.android.support:customtabs:23.0.1.
> Searched in the following locations:
>     file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/support/customtabs/23.0.1/customtabs-23.0.1.pom
>     file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/support/customtabs/23.0.1/customtabs-23.0.1.jar
>     https://jcenter.bintray.com/com/android/support/customtabs/23.0.1/customtabs-23.0.1.pom
>     https://jcenter.bintray.com/com/android/support/customtabs/23.0.1/customtabs-23.0.1.jar
> Required by:
>     project : > com.microsoft.azure:azure-mobile-android:3.2.0
> 
> Please install the Android Support Repository from the Android SDK Manager.

I have tried adding this to my project's gradle:

    classpath 'com.microsoft.azure:azure-mobile-android:3.2.0'

I have tried specifically downloading the support library for 23.0.1. 

I have these other support libraries references in my app's gradle:

    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:percent:25.3.1'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:support-v13:25.3.1'

I have no idea whether upgrading to `3.2.0` will even solve the primary issue, but shouldn't it be easier to upgrade to newer versions of the Android client SDK?

So, first issue is that I don't see how to finish the tutorial to get messaging into my app.
Second issue is that I don't see how to upgrade to the latest Android client SDK.

**Comment by dhei** [comment]
Hi @michael-snapptec, you can follow the [tutorial](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-android-get-started-users#add-authentication-to-the-app) to setup authentication with your Android app. We updated it last Friday to reflect the latest changes of chrome custom tabs login in v3.2.0, so you should be good by following that tutorial.

To answer your question, you would need these dependencies in your Module's build.gradle (as opposed to your Project's build.gradle):

```gradle
dependencies {
    // ... ...
    compile 'com.microsoft.azure:azure-mobile-android:3.2.0@aar'
    compile 'com.android.support:customtabs:23.0.1'
}

```

Let me know if this resolves your issue or not.

**Comment by michael-snapptec** [comment]
Hi @dhei, that appears to have solved the immediate issue of allowing the gradle build to complete. I did end up having to use the following code:

    dependencies {
        compile 'com.microsoft.azure:azure-mobile-android:3.2.0@aar'
        compile 'com.android.support:customtabs:25.3.1'
    }

This seems to be working now, however, the other code to implement the PUSH notifications is still broken. I'm still getting the following error:

    Error:(3, 48) error: package com.microsoft.windowsazure.notifications does not exist

**Comment by dhei** [comment]
@michael-snapptec: Have you tried to add azure-notifications-handler:1.0.1 to your dependencies like this? 

```gradle
dependencies {
    // ... ...
    compile 'com.microsoft.azure:azure-mobile-android:3.2.0@aar'
    compile 'com.microsoft.azure:azure-notifications-handler:1.0.1@jar'
    compile 'com.android.support:customtabs:25.3.1'
}
```

**Comment by michael-snapptec** [comment]
@dhei That worked! I am confused, though. I'm more of an iOS developer, so maybe this is just more common Android knowledge, but where would I have seen that information, to know to add that line? I don't think I've seen that listing in any code example or tutorial I've read. Did I just miss it?

**Comment by dhei** [comment]
Glad it worked for you. 

If you navigate to Azure Mobile Apps quickstart of Android on https://porta.azure.com, you should be able to download and use it as the starting point of integrating Mobile Apps features. You may find the open sourced code of Android quickstart [here](https://github.com/Azure/azure-mobile-apps-quickstarts/tree/master/client/android), and even the [build.gradle](https://github.com/Azure/azure-mobile-apps-quickstarts/blob/master/client/android/ZUMOAPPNAME/app/build.gradle) file.

**Comment by dhei** [comment]
Close this issue.
