### ISSUE TITLE
Need to specify PullStrategy top higher than 50

### ISSUE THREAD

**Issue by DriesPeeters** [Azure/azure-mobile-apps-android-client#95]
We are using the library to sync data from our server to our android apps.
A lot of data need to be synced. Currently the maximum amount of items pulled per request is 50.

In our app we need to be able to specify a higher 'top' for performance issues.
Please make it possible to adjust the top size of the query to be higher than 50.

Already posted the following stackoverflow issue: http://stackoverflow.com/questions/42652523/azure-mobile-app-android-enablequerypagesize

**Comment by elamalani** [comment]
Addressed in #101
