### ISSUE TITLE
Problems with sdk library in eclipse

### ISSUE THREAD

**Issue by adegolyer** [Azure/azure-mobile-apps-android-client#96]
Importing the sdk library as a .jar in eclipse results in unable to find explicit activity class /com.microsoft.windowsazure.mobileservices.authentication.CustomTabsIntermediateActivity errors.

Adding this value to the projects manifest does not fix the issue.

**Comment by elamalani** [comment]
@adegolyer We never tested the SDK using Eclipse as we have always used Android Studio.
